name: 'user-web'
port: 8080
host: "192.168.153.152"
user_srv:
  name: 'user_srv'

jwt:
  key : 'khmfITUwoarekuhn2P0J%kQzs54#IPU2'

redis:
  host: '192.168.131.129'
  port: 6379
  password : '123456'
  db : 1
consul:
  host: "192.168.131.129"
  port: 8500
